helm:
  parameters:
  - name: frontend.image
    value: zhangrui20200722/frontend
    forcestring: true
  - name: frontend.tag
    value: "2682590"
    forcestring: true
  - name: backend.image
    value: zhangrui20200722/backend
    forcestring: true
  - name: backend.tag
    value: "2682590"
    forcestring: true
